services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kinotes'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '${POSTGRES_PORT}::5431'
